/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.*;
import eje2.*;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.*;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Period;
import java.util.ArrayList;
import java.util.logging.*;
import static javax.swing.JOptionPane.*;
import javax.swing.JTextField;

/**
 *
 * @author TaNiA
 */
public class VP extends javax.swing.JFrame {
    
    private static ArrayList<JTextField> listacuadros = new ArrayList();
            
    public VP() {
        initComponents();
        
        //Cambiar color de fondo
           getContentPane().setBackground(new java.awt.Color(51, 158, 0));
        
        //LlenarCampos de fechas
            llenarcampo();
            
        //LlenarArrayList de JTextField
            listacuadros.add(jtNombre);
            listacuadros.add(jtApellidos);
            listacuadros.add(jtTelefono);
            listacuadros.add(jtCorreo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpTarifa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jrFamiliar = new javax.swing.JRadioButton();
        jrIndividual = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDia = new javax.swing.JComboBox<>();
        jMes = new javax.swing.JComboBox<>();
        bBorrar = new javax.swing.JButton();
        jAñoNac = new javax.swing.JComboBox();
        jtNombreHij = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        ErrHijo = new javax.swing.JLabel();
        DatosHijo = new javax.swing.JLabel();
        bAñadir = new javax.swing.JButton();
        bInscribir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Enlace = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtApellidos = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ErrCampo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bIcon1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hoja de Inscripción");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Si, deseo/deseamos hacerme/hacernos socio/s del Zoo-Club. Cuota de ingrereso 15€");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Categoría:");

        OpTarifa.add(jrFamiliar);
        jrFamiliar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jrFamiliar.setText("Familiar: 65€");
        jrFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFamiliarActionPerformed(evt);
            }
        });

        OpTarifa.add(jrIndividual);
        jrIndividual.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jrIndividual.setText("Individual: 32€");
        jrIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrIndividualActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Telefono:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 153, 0)));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha de Nac.:");

        jDia.setEnabled(false);

        jMes.setEnabled(false);

        bBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconox.jpg"))); // NOI18N
        bBorrar.setBorder(null);
        bBorrar.setEnabled(false);
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        jAñoNac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jAñoNac.setEnabled(false);

        jtNombreHij.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNombreHij, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAñoNac, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jMes, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAñoNac, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtNombreHij, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        ErrHijo.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(ErrHijo)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ErrHijo)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        DatosHijo.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(DatosHijo)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(DatosHijo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bAñadir.setForeground(new java.awt.Color(51, 153, 0));
        bAñadir.setText("Añadir Hijo");
        bAñadir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAñadir.setEnabled(false);
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });

        bInscribir.setBackground(new java.awt.Color(102, 255, 102));
        bInscribir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bInscribir.setForeground(new java.awt.Color(51, 102, 255));
        bInscribir.setText("Incribirse");
        bInscribir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bInscribir.setEnabled(false);
        bInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscribirActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 0));
        jLabel11.setText("Atención! Esta es una hoja de inscripción de ejemplo, si desea realmene Inscribirse ");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("al Zoo-Club de Barcelona, pinche en el siguiente enlace");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Hijos: (solo menores de edad y en categoría familiar)");

        Enlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EnlaceMousePressed(evt);
            }
        });

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidosActionPerformed(evt);
            }
        });

        jtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelefonoActionPerformed(evt);
            }
        });

        jtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCorreoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Correo Electronico:");

        ErrCampo.setForeground(new java.awt.Color(204, 0, 0));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenDos.png"))); // NOI18N
        jButton2.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(90, 90, 90)
                                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrFamiliar)
                                        .addGap(24, 24, 24)
                                        .addComponent(jrIndividual)))
                                .addGap(66, 66, 66)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(bInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bAñadir)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Enlace))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(ErrCampo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrFamiliar)
                    .addComponent(jrIndividual))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(ErrCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(bInscribir)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Enlace))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        bIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenUno.jpg"))); // NOI18N
        bIcon1.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(bIcon1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarcampo()
    {
        llenardiaymes(jDia,31);
        llenardiaymes(jMes,12);
        llenaraño();
    }
    
    public void llenardiaymes(javax.swing.JComboBox j,int v)
    {
        j.removeAllItems();
        
        for (int x=1;x<=v;x++)
        {
            j.addItem(x);
        }
        
        j.setSelectedIndex(-1);
    }
    
    public void llenaraño()
    {
        jAñoNac.removeAllItems();
        
        LocalDate fecha = LocalDate.now();
        int año = fecha.getYear();

        for (int x=0;x<=18;x++)
        {
            jAñoNac.addItem(año);
            año -= 1;
        }
        
        jAñoNac.setSelectedIndex(-1);
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Enlace.setText("<html><a href=; style=color:green;>Zoo de Barcelona</a></html>");
    }//GEN-LAST:event_formWindowActivated

    private void EnlaceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnlaceMousePressed
        Desktop enlace = Desktop.getDesktop();
        
        try {
            enlace.browse(new URI("https://www.zoobarcelona.cat/es/collabora/zoo-club"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(VP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EnlaceMousePressed

    private void jrFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFamiliarActionPerformed
        bInscribir.setEnabled(true);
    }//GEN-LAST:event_jrFamiliarActionPerformed
    
    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        if (Eje2.comprobarhijo() == 0)
            showMessageDialog(this,"NO HAY HIJOS AÑADIDOS");
        else
            Eje2.abrirborrar();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void jrIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrIndividualActionPerformed
        bInscribir.setEnabled(true);
        jtNombreHij.setEnabled(false);
        jDia.setEnabled(false);
        jMes.setEnabled(false);
        jAñoNac.setEnabled(false);
        bBorrar.setEnabled(false);
        bAñadir.setEnabled(false);
    }//GEN-LAST:event_jrIndividualActionPerformed

    private void bInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscribirActionPerformed
        try
        {
            if (jtNombre.getText().isEmpty() || jtApellidos.getText().isEmpty() || jtTelefono.getText().isEmpty() || jtCorreo.getText().isEmpty())
              throw new CampoObligatorio();  
                        
            validarnombre(jtNombre);
            defecto(jtNombre);
            validarapellidos();
            if (Eje2.comprobarsocio() != 0)
            {
                if (Eje2.comprobarsiexiste(jtNombre.getText().toUpperCase(),jtApellidos.getText().toUpperCase()))
                throw new Existente();
            }
            
            defecto(jtNombre);
            defecto(jtApellidos);
                    
            validartelefono();
            defecto(jtTelefono);
            validarcorreo();
            defecto(jtCorreo);
            ErrCampo.setText("");
            
            if (jrFamiliar.isSelected())
            {
                try
                {
                    if (Eje2.comprobarhijo() == 0)
                        throw new HijoError();
                    else
                    {    
                        ErrHijo.setText("");
                        Eje2.añadirsociofam(jtNombre.getText().toUpperCase(),jtApellidos.getText().toUpperCase(),jtTelefono.getText(),jtCorreo.getText()); 
                        showMessageDialog(this,"ALTA DE SOCIO CORRECTA");
                        limp();
                        Eje2.crearlista();
                    }           
                }
                catch (HijoError he)
                {
                    ErrHijo.setText("DEBES AÑADIR UN HIJO MINIMO");
                    jtNombreHij.setEnabled(true);
                    jtNombreHij.requestFocus();
                    jDia.setEnabled(true);
                    jMes.setEnabled(true);
                    jAñoNac.setEnabled(true);
                    bBorrar.setEnabled(true);
                    bAñadir.setEnabled(true);
                }
            }     
            else
            {
                Eje2.añadirsocioindi(jtNombre.getText().toUpperCase(),jtApellidos.getText().toUpperCase(),jtTelefono.getText(),jtCorreo.getText());
                showMessageDialog(this,"ALTA CORRECTA DEL SOCIO"); 
                limp();
            }
        }
        catch (CampoObligatorio npe)
        {
            showMessageDialog(this,"QUEDAN CAMPOS OBLIGATORIOS POR COMPLETAR");
        }
        catch(DatoNoValido dnv)
        {
            ErrCampo.setText(dnv.getCampo());
            dnv.getCuadro().setBackground(Color.RED);
            dnv.getCuadro().requestFocus();
            dnv.getCuadro().setEnabled(true);
        }
        catch (Existente e)
        {
            jtNombre.setBackground(Color.RED);
            jtApellidos.setBackground(Color.RED);
            jtNombre.setEnabled(true);
            jtApellidos.setEnabled(true);
            jtNombre.requestFocus();
            ErrCampo.setText("ESTA PERSONA YA ESTA DADA DE ALTA");
        }
    }//GEN-LAST:event_bInscribirActionPerformed

    public void limp()
    {
        for (int x=0;x<listacuadros.size();x++)
            {
               limpiar(listacuadros.get(x));
            }
    }
    
    public void limpiar(javax.swing.JTextField jt)
    {
       jt.setText("");
       jt.setEnabled(true);
       jtNombre.requestFocus();
       OpTarifa.clearSelection();
    }
    
    public void validarnombre(javax.swing.JTextField jt) throws DatoNoValido
    {   
        if (!Eje2.expreregular(jt.getText().toUpperCase(),"^[A-Z]+$"))
            throw new DatoNoValido("NOMBRE INCORRECTO (SOLO LETRAS)",jt);
    }
    
    public void validarapellidos() throws DatoNoValido
    {   
        if (!Eje2.expreregular(jtApellidos.getText().toUpperCase(),"^[A-Z]+\\s[A-Z]+$"))
            throw new DatoNoValido("APELLIDOS INCORRECTO (LOS DOS APELLIDOS)",jtApellidos);     
    }
    
    public void validartelefono() throws DatoNoValido
    {
        if (!Eje2.expreregular(jtTelefono.getText(),"^[6|7][\\d]{8}$"))
            throw new DatoNoValido("TELEFONO INCORRECTO",jtTelefono);   
    }
    
    public void validarcorreo() throws DatoNoValido
    {
        if (!Eje2.expreregular(jtCorreo.getText(),"^[-a-zA-z0-9_]+(.[-a-zA-Z0-9_]+)*@(gmail|hotmail).(com|es|org)$"))
            throw new DatoNoValido("CORREO ELECTRONICO INCORRECTO",jtCorreo);
        
        if (Eje2.comprobarcorreo(jtCorreo.getText()))
            throw new DatoNoValido("CORREO YA EXISTENTE",jtCorreo);
    }
    
    public void defecto(javax.swing.JTextField j)
    {
        j.setBackground(Color.WHITE);
        j.setEnabled(false);
    }
    
    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        try
        {
          ErrHijo.setText("");
          
          if (jtNombreHij.getText().isEmpty() || jDia.getSelectedIndex() == -1 || jMes.getSelectedIndex() == -1 || jAñoNac.getSelectedIndex() == -1)
              throw new CampoObligatorio();
          
          validarnombre(jtNombreHij);
          jtNombreHij.setBackground(Color.WHITE);
          LocalDate fecha = validarfecha();
          
          Eje2.añadirhijo(jtNombreHij.getText(),fecha);
          showMessageDialog(this,"HIJ@ AÑADID@");
          
          DatosHijo.setText("");
          jtNombreHij.setBackground(Color.WHITE);
          jtNombreHij.setText("");
          jDia.setSelectedIndex(-1);
          jMes.setSelectedIndex(-1);
          jAñoNac.setSelectedIndex(-1);
        }
        catch (CampoObligatorio co)
        {
            showMessageDialog(this,"QUEDAN CAMPOS OBLIGATORIOS POR RELLENAR");
        }
        catch (DatoNoValido dnv)
        {
            jtNombreHij.setBackground(Color.RED);
            DatosHijo.setText(dnv.getCampo());
        }
        catch (FechaNoValida | DateTimeException dte)
        {
            DatosHijo.setText("FECHA INCORRECTA");
        }
    }//GEN-LAST:event_bAñadirActionPerformed

    public LocalDate validarfecha() throws FechaNoValida
    {
        int dia = Integer.parseInt(jDia.getSelectedItem().toString());
        int mes = Integer.parseInt(jMes.getSelectedItem().toString());
        int año = Integer.parseInt(jAñoNac.getSelectedItem().toString());
        
        LocalDate fecha;
        fecha = LocalDate.of(año, mes, dia);
        
        if (fecha.isAfter(LocalDate.now()))
            throw new FechaNoValida();
        
        Period periodo = Period.between(fecha, LocalDate.now());
        if (periodo.getYears() >=18)
            throw new FechaNoValida();
        
        return fecha;
    }    
    
    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
       jtApellidos.requestFocus();
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellidosActionPerformed
       jtTelefono.requestFocus();
    }//GEN-LAST:event_jtApellidosActionPerformed

    private void jtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelefonoActionPerformed
       jtCorreo.requestFocus();
    }//GEN-LAST:event_jtTelefonoActionPerformed

    private void jtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCorreoActionPerformed
        if (jrFamiliar.isSelected())
        {
            jtNombreHij.requestFocus();
            jtNombre.setEnabled(false);
            jtApellidos.setEnabled(false);
            jtTelefono.setEnabled(false);
            jtCorreo.setEnabled(false);
            jtNombreHij.setEnabled(true);
            jDia.setEnabled(true);
            jMes.setEnabled(true);
            jAñoNac.setEnabled(true);
            bAñadir.setEnabled(true);
            bBorrar.setEnabled(true);
        }
        else
            bInscribir.requestFocus();
    }//GEN-LAST:event_jtCorreoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (Eje2.comprobarsocio() == 0)
            System.exit(0);
        else
            showMessageDialog(this,Eje2.mostrardatossocio());
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatosHijo;
    private javax.swing.JLabel Enlace;
    private javax.swing.JLabel ErrCampo;
    private javax.swing.JLabel ErrHijo;
    private javax.swing.ButtonGroup OpTarifa;
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bIcon1;
    private javax.swing.JButton bInscribir;
    private javax.swing.JComboBox jAñoNac;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jMes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jrFamiliar;
    private javax.swing.JRadioButton jrIndividual;
    private javax.swing.JTextField jtApellidos;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtNombreHij;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
