/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import eje1.*;
import java.awt.Color;
import java.util.regex.*;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author taniagarcia
 */
public class VPersonas extends javax.swing.JDialog {

    private static int cont;
    private static int tlista;
    private static String operacion;
    
    public VPersonas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public VPersonas(java.awt.Frame parent, boolean modal, String operacion)
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        try
        {
            this.operacion = operacion;
            
            if (operacion.equals("Registrar"))
            {
                comp(true,false);
                tfNombre.requestFocus();
                tfEdad.setEditable(false);
                tfProfesion.setEditable(false);
                tfTelefono.setEditable(false);
            } 
            else
              comp(false,true);
            
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage());
        }
    }
    
    public void comp(boolean valor,boolean b)
    {
        tfNombre.setEditable(valor);
        bAceptar.setEnabled(false);
        bIzq.setEnabled(b);
        bDer.setEnabled(b);
        bSalir.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfEdad = new javax.swing.JTextField();
        tfProfesion = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        bIzq = new javax.swing.JButton();
        bDer = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        jlErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Personas");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Profesión");

        jLabel5.setText("Teléfono");

        tfNombre.setEditable(false);
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfEdad.setEditable(false);
        tfEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEdadActionPerformed(evt);
            }
        });

        tfProfesion.setEditable(false);
        tfProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProfesionActionPerformed(evt);
            }
        });

        tfTelefono.setEditable(false);
        tfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoActionPerformed(evt);
            }
        });

        bIzq.setText("<");
        bIzq.setEnabled(false);
        bIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIzqActionPerformed(evt);
            }
        });

        bDer.setText(">");
        bDer.setEnabled(false);
        bDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDerActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.setEnabled(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        jlErr.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                .addComponent(tfProfesion, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jlErr)))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bIzq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bDer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bSalir)))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addComponent(jlErr)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIzq)
                    .addComponent(bDer)
                    .addComponent(bSalir))
                .addGap(18, 18, 18)
                .addComponent(bAceptar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try 
        {
            Eje1.insertarpersona(tfNombre.getText().toUpperCase(),tfEdad.getText(),tfProfesion.getText(),tfTelefono.getText());
            showMessageDialog(this,"Alta Registrada");
            Eje1.ventanap(this);
        } 
        catch (Exception e) 
        {
            showMessageDialog(this,e.getMessage());
        }    
    }//GEN-LAST:event_bAceptarActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        try
        {
            if (tfNombre.getText().isEmpty())
                throw new Exception("CAMPO OBLIGATORIO");
            if (!validardato(tfNombre.getText().toUpperCase(),"^[A-Z]+$"))
                throw new Exception("NOMBRE INCORRECTO");
            if (Eje1.consultarpersona(tfNombre.getText().toUpperCase()))
                throw new Exception("EL NOMBRE YA ESTA EN LA BD");
            
            defecto(tfNombre,tfEdad);
        }
        catch (Exception e)
        {
            error(tfNombre,e);
        }    
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEdadActionPerformed
        try
        {
            if (tfEdad.getText().isEmpty())
                throw new Exception("CAMPO OBLIGATORIO");
            if(!validardato(tfEdad.getText(),"^[1-9][0-9]?$"))
                throw new Exception("EDAD INCORRECTA");
            
            defecto(tfEdad,tfProfesion);
        }
        catch (Exception e)
        {
            error(tfEdad,e);
        }
    }//GEN-LAST:event_tfEdadActionPerformed

    public void error(javax.swing.JTextField tf,Exception e)
    {
        jlErr.setText(e.getMessage());
        tf.setBackground(Color.red);
    }
    
    private void tfProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProfesionActionPerformed
        try
        {
            if (tfProfesion.getText().isEmpty())
                throw new Exception("CAMPO OBLIGATORIO");
            if(!validardato(tfProfesion.getText().toUpperCase(),"^[A-Z]+( [A-Z]+)*$"))
                throw new Exception("PROFESION INCORRECTA");
            
            defecto(tfProfesion,tfTelefono);
        }
        catch (Exception e)
        {
            error(tfProfesion,e);
        }
    }//GEN-LAST:event_tfProfesionActionPerformed

    private void tfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoActionPerformed
       try
        {
            if (tfTelefono.getText().isEmpty())
                throw new Exception("CAMPO OBLIGATORIO");
            if(!validardato(tfTelefono.getText().toUpperCase(),"^[6|7][\\d]{8}$"))
                throw new Exception("TELEFONO INCORRECTO");
            
           jlErr.setText("");
           tfTelefono.setBackground(Color.WHITE);
           tfTelefono.setEnabled(false);
           bAceptar.setEnabled(true);
           bAceptar.requestFocus();
        }
        catch (Exception e)
        {
            error(tfTelefono,e);
        }
    }//GEN-LAST:event_tfTelefonoActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        try 
        {
            Eje1.ventanap(this);
        } 
        catch (Exception ex) 
        {
            showMessageDialog(this,ex.getMessage());
        }
    }//GEN-LAST:event_bSalirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (operacion.equals("Consultar"))
        {
            cont = 1;
            mostrardatos();
            bIzq.setEnabled(false);

            try 
            {
                tlista = Eje1.personasreg();
                if (tlista ==1)
                   bDer.setEnabled(false);

            } 
            catch (Exception e) {
                showMessageDialog(this,e.getMessage());
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void bDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDerActionPerformed
        cont++;
        bIzq.setEnabled(true);
        if (cont == tlista)
            bDer.setEnabled(false);
        mostrardatos();
    }//GEN-LAST:event_bDerActionPerformed

    private void bIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIzqActionPerformed
        cont--;
        bDer.setEnabled(true);
        if (cont == 1)
            bIzq.setEnabled(false);
        mostrardatos();
    }//GEN-LAST:event_bIzqActionPerformed

    public void mostrardatos()
    {
        tfNombre.setText(Eje1.mostrarnombre(cont-1));
        tfEdad.setText(Eje1.mostraredad(cont-1));
        tfProfesion.setText(Eje1.mostrarprofesion(cont-1));
        tfTelefono.setText(Eje1.mostrartelefono(cont-1));
    }
    
    public void defecto(javax.swing.JTextField tf, javax.swing.JTextField td)
    {
        jlErr.setText("");
        tf.setBackground(Color.WHITE);
        tf.setEnabled(false);
        td.setEditable(true);
        td.requestFocus();
    }
        
    private boolean validardato(String dato,String expre)
    {
        Pattern pt = Pattern.compile(expre);
        Matcher m = pt.matcher(dato);
        return m.matches();  
        /*
            if (!m.matches())
                return false;
            return true;  
        */
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VPersonas dialog = new VPersonas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bDer;
    private javax.swing.JButton bIzq;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlErr;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfProfesion;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
