/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import eje1.*;

/**
 *
 * @author TaNiA
 */
public class VP extends javax.swing.JFrame {

    private static double primernumero;
    private static double segundonumero;    
    private static String operador;
    private static String n;
    private static double resultado;
    private static int cont = 0;
    
    public VP() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCero = new javax.swing.JButton();
        jComa = new javax.swing.JButton();
        jUno = new javax.swing.JButton();
        jDos = new javax.swing.JButton();
        jTres = new javax.swing.JButton();
        jDivi = new javax.swing.JButton();
        jCuatro = new javax.swing.JButton();
        jCinco = new javax.swing.JButton();
        jSeis = new javax.swing.JButton();
        jMulti = new javax.swing.JButton();
        jSiete = new javax.swing.JButton();
        jOcho = new javax.swing.JButton();
        jNueve = new javax.swing.JButton();
        jResta = new javax.swing.JButton();
        jBorrar = new javax.swing.JButton();
        jSuma = new javax.swing.JButton();
        jIgual = new javax.swing.JButton();
        jTexto = new javax.swing.JTextField();
        tfEti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCero.setText("0");
        jCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCeroActionPerformed(evt);
            }
        });

        jComa.setText(",");
        jComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComaActionPerformed(evt);
            }
        });

        jUno.setText("1");
        jUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnoActionPerformed(evt);
            }
        });

        jDos.setText("2");
        jDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDosActionPerformed(evt);
            }
        });

        jTres.setText("3");
        jTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTresActionPerformed(evt);
            }
        });

        jDivi.setText("/");
        jDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiviActionPerformed(evt);
            }
        });

        jCuatro.setText("4");
        jCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCuatroActionPerformed(evt);
            }
        });

        jCinco.setText("5");
        jCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCincoActionPerformed(evt);
            }
        });

        jSeis.setText("6");
        jSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeisActionPerformed(evt);
            }
        });

        jMulti.setText("*");
        jMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiActionPerformed(evt);
            }
        });

        jSiete.setText("7");
        jSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSieteActionPerformed(evt);
            }
        });

        jOcho.setText("8");
        jOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOchoActionPerformed(evt);
            }
        });

        jNueve.setText("9");
        jNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNueveActionPerformed(evt);
            }
        });

        jResta.setText("-");
        jResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestaActionPerformed(evt);
            }
        });

        jBorrar.setText("C");
        jBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarActionPerformed(evt);
            }
        });

        jSuma.setText("+");
        jSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSumaActionPerformed(evt);
            }
        });

        jIgual.setText("=");
        jIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIgualActionPerformed(evt);
            }
        });

        jTexto.setEditable(false);
        jTexto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfEti.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTexto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jUno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTres, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jResta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(jIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(tfEti)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(tfEti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBorrar)
                            .addComponent(jSuma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSiete)
                            .addComponent(jOcho)
                            .addComponent(jNueve)
                            .addComponent(jResta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCuatro)
                            .addComponent(jCinco)
                            .addComponent(jSeis)
                            .addComponent(jMulti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUno)
                            .addComponent(jDos)
                            .addComponent(jTres)
                            .addComponent(jDivi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCero)
                            .addComponent(jComa))
                        .addGap(91, 91, 91))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTresActionPerformed
        jTexto.setText(jTexto.getText()+"3");
    }//GEN-LAST:event_jTresActionPerformed

    private void jUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnoActionPerformed
        jTexto.setText(jTexto.getText()+"1");
    }//GEN-LAST:event_jUnoActionPerformed

    private void jDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDosActionPerformed
        jTexto.setText(jTexto.getText()+"2");
    }//GEN-LAST:event_jDosActionPerformed

    private void jCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCuatroActionPerformed
        jTexto.setText(jTexto.getText()+"4");
    }//GEN-LAST:event_jCuatroActionPerformed

    private void jCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCeroActionPerformed
        jTexto.setText(jTexto.getText()+"0");
    }//GEN-LAST:event_jCeroActionPerformed

    private void jCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCincoActionPerformed
       jTexto.setText(jTexto.getText()+"5");
    }//GEN-LAST:event_jCincoActionPerformed

    private void jSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeisActionPerformed
        jTexto.setText(jTexto.getText()+"6");
    }//GEN-LAST:event_jSeisActionPerformed

    private void jSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSieteActionPerformed
       jTexto.setText(jTexto.getText()+"7");
    }//GEN-LAST:event_jSieteActionPerformed

    private void jOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOchoActionPerformed
        jTexto.setText(jTexto.getText()+"8");
    }//GEN-LAST:event_jOchoActionPerformed

    private void jNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNueveActionPerformed
        jTexto.setText(jTexto.getText()+"9");
    }//GEN-LAST:event_jNueveActionPerformed

    private void jBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarActionPerformed
         jTexto.setText("");
         primernumero = 0;
         segundonumero = 0;
         operador = null;
         tfEti.setText("");
         
    }//GEN-LAST:event_jBorrarActionPerformed

    private void jComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComaActionPerformed
        if (Eje1.comprobarvacio(jTexto))
            jTexto.setText(jTexto.getText()+"0.");
        else{
            if (Eje1.comprobarcoma(jTexto,".")){}
            else
                jTexto.setText(jTexto.getText()+".");
        }
    }//GEN-LAST:event_jComaActionPerformed
        
    private void jSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumaActionPerformed
        funcion("+");
        tfEti.setText(primernumero + operador);
        cont = 0;
    }//GEN-LAST:event_jSumaActionPerformed

    private void jIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIgualActionPerformed
       try
       {
        if (Eje1.comprobarvacio(jTexto))
            jTexto.setText("0");
        else
        {   
            switch (operador)
            {
                 case "+":
                     funcionsuma();
                  break;
                 case "-":
                     funcionresta();
                  break;
                 case "*":
                     funcionmulti();
                  break;
                 default:
                     funciondivi();                    
            }
        } 
       }
       catch (NullPointerException npe)
       {
           jTexto.setText("0");
       }
    }//GEN-LAST:event_jIgualActionPerformed

    public void funcionsuma()
    {
        if (cont >= 1)
        {
            comuni();
            resultado = primernumero + segundonumero;
            comunf();
        }
        else
        {
            segundonumero = Double.parseDouble(jTexto.getText());   
            resultado = primernumero + segundonumero;
            convertircoma();  
            tfEti.setText(tfEti.getText() + segundonumero + " = " + resultado);
        }
      cont ++; 
    }
    
    public void funcionresta()
    {
        if (cont >= 1)
          {
            comuni();
            resultado = primernumero - segundonumero;
            comunf();
          }
        else
            {
              segundonumero = Double.parseDouble(jTexto.getText());   
              resultado = primernumero - segundonumero;
              convertircoma();  
              tfEti.setText(tfEti.getText() + segundonumero + " = " + resultado);
            }
      cont ++; 
    }
    
    public void funcionmulti()
    {
        if (cont >= 1)
          {
            comuni();
            resultado = primernumero * segundonumero;
            comunf();
          }
        else
            {
              segundonumero = Double.parseDouble(jTexto.getText());   
              resultado = primernumero * segundonumero;
              convertircoma();  
              tfEti.setText(tfEti.getText() + segundonumero + " = " + resultado);
            }
      cont ++; 
    }
    
    public void funciondivi()
    {
        if (cont >= 1)
          {
            comuni();
            resultado = primernumero / segundonumero;
            comunf();
          }
        else
            {
              segundonumero = Double.parseDouble(jTexto.getText());   
              resultado = primernumero / segundonumero;
              convertircoma();  
              tfEti.setText(tfEti.getText() + segundonumero + " = " + resultado);
            }
      cont ++; 
    }
    
    public void comuni()
    {
      resultado = Double.parseDouble(jTexto.getText());
      primernumero = resultado;  
    }
    
    public void comunf()
    {
        tfEti.setText("");
        jTexto.setText(String.valueOf(resultado));
        tfEti.setText(primernumero + operador + segundonumero + " = " + resultado);
    }
    
    public void convertircoma()
    {
        n =  String.valueOf(resultado);
        resultado = Double.parseDouble(n.replace(",", "."));
        jTexto.setText(String.valueOf(resultado));
    }
    
    private void jRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestaActionPerformed
        funcion("-");
        tfEti.setText(primernumero + operador);
        cont = 0;
    }//GEN-LAST:event_jRestaActionPerformed

    private void jMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiActionPerformed
        funcion("*");
        tfEti.setText(primernumero + operador);
        cont = 0;
    }//GEN-LAST:event_jMultiActionPerformed

    private void jDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiviActionPerformed
        funcion("/");
        tfEti.setText(primernumero + operador);
        cont = 0;
    }//GEN-LAST:event_jDiviActionPerformed

    public void funcion(String ope)
    {
        if (Eje1.comprobarvacio(jTexto))
            jTexto.setText("0");
        else
        {
            primernumero = Double.parseDouble(jTexto.getText());
            operador = ope;
            jTexto.setText("");
        }  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBorrar;
    private javax.swing.JButton jCero;
    private javax.swing.JButton jCinco;
    private javax.swing.JButton jComa;
    private javax.swing.JButton jCuatro;
    private javax.swing.JButton jDivi;
    private javax.swing.JButton jDos;
    private javax.swing.JButton jIgual;
    private javax.swing.JButton jMulti;
    private javax.swing.JButton jNueve;
    private javax.swing.JButton jOcho;
    private javax.swing.JButton jResta;
    private javax.swing.JButton jSeis;
    private javax.swing.JButton jSiete;
    private javax.swing.JButton jSuma;
    private javax.swing.JTextField jTexto;
    private javax.swing.JButton jTres;
    private javax.swing.JButton jUno;
    private javax.swing.JLabel tfEti;
    // End of variables declaration//GEN-END:variables
}
