/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.*;
import eje1.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.*;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author taniagarcia
 */
public class VOpera extends javax.swing.JFrame {
    //Guardar la posicion del radio    
        private static int z;
    
    //ArrayList para guardar los N radiobuttons que representan las N cuentas
        private ArrayList<JRadioButton> aRadios;
        private int pos;
        
    //Variable que me undica si es una consulta o un movimiento
        private String operacion;
        
    //Creamos el buttongroup
         ButtonGroup gCuentas = new ButtonGroup();
    
    //Variable donde indicamos el desplazamiento inicial
        private int desplazamiento = 20;
    
    //Creacion de objetos
        private JRadioButton radio;
        private JLabel etiquetas;  
        
        private ArrayList<JLabel> listaetiquetas = new ArrayList();
        
        private static NumberFormat nf = NumberFormat.getNumberInstance(Locale.ROOT);
    
    public VOpera() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Crear y llenar el arraylist con tantos radios como cuentas tenga el cliente
            crearArrayRadios();
        
        //Ocultar los movimientos,cuentas y saldos
            pCuenta.setVisible(false);
            pMov.setVisible(false);
            pTran.setVisible(false);
            lSaldo.setVisible(false);  
    }
    
    private void crearArrayRadios()
    {
        //Creo el array, lo lleno e inicialmente oculto sus elementos
            aRadios = new ArrayList();
        
        //Crear tantos radios como sea necesario
            for (pos = 0; pos < Eje1.numcuentas();pos++)
            {
                //Crear el radio y añadirlo al arrayList
                    radio = new javax.swing.JRadioButton();
                    aRadios.add(radio);
                    
                //Establecimiento de la propiedad text para que muestre el numero de cuenta
                    radio.setText(Eje1.numcuenta(pos));
                
                //Añadirlo al buttonGroup
                    gCuentas.add(radio);
                    
                //Evento actionPerformed
                    radio.addActionListener(new java.awt.event.ActionListener()
                    {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                            radioActionPerformed(evt);
                        }
                    });
                    
                //Colocar los radios    
                    colocar();
                
                //Recolocar todos los elementos dentro de la interfaz grafica
                    pack();
                
                //Mover para que el siguiente salga debajo
                    desplazamiento+=20;
            }
    }
    
    private void colocar()
    {
        //Colocar el radio dentro del panel
            javax.swing.GroupLayout pCuentaLayout = new javax.swing.GroupLayout(pCuenta);
            pCuenta.setLayout(pCuentaLayout);
            pCuentaLayout.setHorizontalGroup(
                pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCuentaLayout.createSequentialGroup()
                .addGap(22,22,22)
                .addComponent(radio)
                .addContainerGap(373, Short.MAX_VALUE))      
            );
            pCuentaLayout.setVerticalGroup(
                pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCuentaLayout.createSequentialGroup()
                .addGap(desplazamiento,desplazamiento,desplazamiento)
                .addComponent(radio)
                .addContainerGap(92, Short.MAX_VALUE))        
            );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bConsulta = new javax.swing.JButton();
        bMovimiento = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        pCuenta = new javax.swing.JPanel();
        pMov = new javax.swing.JPanel();
        lSaldo = new javax.swing.JLabel();
        pTran = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcTipo = new javax.swing.JComboBox<>();
        jLabelTipo = new javax.swing.JLabel();
        tfCuenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfImporte = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        miConsulta = new javax.swing.JMenuItem();
        miMovimiento = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMCerrar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar3.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar3.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar4.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar4.add(jMenu14);

        jMenu15.setText("File");
        jMenuBar5.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar5.add(jMenu16);

        jMenu17.setText("File");
        jMenuBar6.add(jMenu17);

        jMenu18.setText("Edit");
        jMenuBar6.add(jMenu18);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bConsulta.setText("Consulta");
        bConsulta.setFocusable(false);
        bConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultaActionPerformed(evt);
            }
        });
        jToolBar1.add(bConsulta);

        bMovimiento.setText("Movimientos");
        bMovimiento.setFocusable(false);
        bMovimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bMovimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMovimientoActionPerformed(evt);
            }
        });
        jToolBar1.add(bMovimiento);

        bCerrar.setText("Cerrar Sesión");
        bCerrar.setFocusable(false);
        bCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(bCerrar);

        pCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuentas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N

        javax.swing.GroupLayout pCuentaLayout = new javax.swing.GroupLayout(pCuenta);
        pCuenta.setLayout(pCuentaLayout);
        pCuentaLayout.setHorizontalGroup(
            pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        pCuentaLayout.setVerticalGroup(
            pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pMov.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N

        javax.swing.GroupLayout pMovLayout = new javax.swing.GroupLayout(pMov);
        pMov.setLayout(pMovLayout);
        pMovLayout.setHorizontalGroup(
            pMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        pMovLayout.setVerticalGroup(
            pMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        lSaldo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lSaldo.setText("Saldo:");

        pTran.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N

        jLabel3.setText("Tipo");

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transferencia", "Pago de Recibo" }));
        jcTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoActionPerformed(evt);
            }
        });

        jLabelTipo.setText("Cuenta de destino");

        jLabel5.setText("Importe");

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pTranLayout = new javax.swing.GroupLayout(pTran);
        pTran.setLayout(pTranLayout);
        pTranLayout.setHorizontalGroup(
            pTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTranLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipo)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAceptar)
                    .addGroup(pTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcTipo, 0, 193, Short.MAX_VALUE)
                        .addComponent(tfCuenta)
                        .addComponent(tfImporte)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        pTranLayout.setVerticalGroup(
            pTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTranLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(tfCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(bAceptar)
                .addGap(26, 26, 26))
        );

        jMenu1.setText("Resumen");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Inversiones");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Tarjetas");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Mercados");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Prestamos");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Seguros");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Servicios");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Cuentas");

        miConsulta.setText("Consulta");
        miConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaActionPerformed(evt);
            }
        });
        jMenu8.add(miConsulta);

        miMovimiento.setText("Movimientos");
        miMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMovimientoActionPerformed(evt);
            }
        });
        jMenu8.add(miMovimiento);

        jMenuBar1.add(jMenu8);

        jMenu19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N

        jMCerrar.setText("Cerrar Sesión");
        jMCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCerrarActionPerformed(evt);
            }
        });
        jMenu19.add(jMCerrar);

        jMenuBar1.add(jMenu19);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(pCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMovimientoActionPerformed
        bMovimiento.doClick();
    }//GEN-LAST:event_miMovimientoActionPerformed

    private void bConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultaActionPerformed
            operacion = "Consulta";
        
        //Muestro las cuentas
            pCuenta.setVisible(true);
        
        //Por si vengo de hacer algun movimiento
            pMov.setVisible(false);
            pTran.setVisible(false);
    }//GEN-LAST:event_bConsultaActionPerformed

    private void bMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMovimientoActionPerformed
            operacion = "Movimientos";
        //Muestro las cuentas
            pCuenta.setVisible(true);
        
        //Por si vengo de alguna consulta
            pMov.setVisible(false);
            lSaldo.setVisible(false);
    }//GEN-LAST:event_bMovimientoActionPerformed

    private void miConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaActionPerformed
        bConsulta.doClick();
    }//GEN-LAST:event_miConsultaActionPerformed

    private void jcTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoActionPerformed
        if (jcTipo.getSelectedIndex() == 1)
            jLabelTipo.setText("Referencia del recibo");
        else
            jLabelTipo.setText("Cuenta destino");
    }//GEN-LAST:event_jcTipoActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        if (datosCorrectos())
        {
            if (jcTipo.getSelectedIndex() == 1)
            {
                Eje1.recibo(tfImporte.getText());
                showMessageDialog(this,"RECIBO PAGADO AL NºRECIBO " + tfCuenta.getText());
            }
            else
            {
                if (Eje1.comprobarsiexistecuenta(tfCuenta.getText()))
                {
                    Eje1.transferenciaex(tfImporte.getText()); 
                    showMessageDialog(this,"TRANSFERENCIA REALIZADA AL Nº DE CUENTA " + tfCuenta.getText());
                }
                else
                {
                    Eje1.transferencia(tfImporte.getText());
                    showMessageDialog(this,"TRANSFERENCIA REALIZADA AL º DE CUENTA " +tfCuenta.getText());
                }
            }
        }
        tfCuenta.setText("");
        tfImporte.setText("");
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
       dispose();
       Eje1.accederp();
    }//GEN-LAST:event_bCerrarActionPerformed

    private void jMCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCerrarActionPerformed
        bCerrar.doClick();
    }//GEN-LAST:event_jMCerrarActionPerformed

    private boolean datosCorrectos()
    {
        try
        {
            if (jcTipo.getSelectedIndex() == 1)
            {
                if (!Eje1.validarformato(tfCuenta.getText().toUpperCase(), "^[\\d]{8}[-][A-Z]{2}$"))
                    throw new DatoNoValido();
            }
            else
            {
                if (!Eje1.validarformato(tfCuenta.getText(), "^[\\d]{20}$"))
                    throw new DatoNoValido();
                
                if (tfCuenta.getText().equals(Eje1.numcuenta(z)))
                    throw new CampoIncorrecto();
            }
            double importe = Double.parseDouble(tfImporte.getText());
            if(importe < 0 || (Eje1.getSaldo() - importe) < 0)
                throw new DatoNoValido();
            return true;
        }
        catch (CampoIncorrecto ci)
        {
            showMessageDialog(this,"NO PUEDES REALIZAR UNA TRANSFERENCIA A TU MISMO NUMERO DE CUENTA");
            return false;
        }
        catch (DatoNoValido dnv)
        {
            showMessageDialog(this,"DATOS NO VALIDOS O NO HAY SALDO");
            return false;
        }
        catch (NumberFormatException e)
        {
            showMessageDialog(this,"DATOS NO VALIDOS");
            return false;
        }
    }
    
    private void radioActionPerformed(java.awt.event.ActionEvent evt)
    {
        //Buscar el radio seleccionado. La posición coindice con la de la cuenta en el arrayList
            for (z = 0; z < aRadios.size() && !aRadios.get(z).isSelected();z++){}
            Eje1.setCuenta(z);
            cuentaSeleccionada(z);
    }
    
    private void cuentaSeleccionada(int c)
    {

        if (operacion.equals("Consulta"))
        {
            //Mostrar movimientos de la cuenta c
                mostrarMovimiento(c);                    
                pMov.setVisible(true);
                lSaldo.setText("Saldo = " + nf.format(Eje1.getSaldo()));
                lSaldo.setVisible(true);
        }
        else
        {
            pTran.setVisible(true);
        }    
    }

    
    public void mostrarMovimiento(int c)
    {
        desplazamiento = 20;
        listaetiquetas.clear();
        pMov.removeAll();
        int nro = Eje1.getnmov();
        
        if (nro <=5)
        {
            for (int x=0;x<nro;x++)
            {
                creareti(x);
            }
        }
        else
        {
            for (int x = 0,cuenta = nro -5; x < 5; x++,cuenta++)
            {
                creareti(cuenta);
            }
        }
    }
    
    public void creareti(int x)
    {
        etiquetas = new JLabel(Eje1.getMovimiento(x));
        listaetiquetas.add(etiquetas);
        colocareti();
        desplazamiento+=25;
        pack();
    }
    
    public void colocareti()
    {
        javax.swing.GroupLayout pMovLayout = new javax.swing.GroupLayout(pMov);
            pMov.setLayout(pMovLayout);
            pMovLayout.setHorizontalGroup(
                pMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pMovLayout.createSequentialGroup()
                .addGap(22,22,22)
                .addComponent(etiquetas)
                .addContainerGap(200, Short.MAX_VALUE))
             );
            pMovLayout.setVerticalGroup(
                pMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pMovLayout.createSequentialGroup()
                .addGap(desplazamiento,desplazamiento,desplazamiento)
                .addComponent(etiquetas)
                .addContainerGap(20, Short.MAX_VALUE))        
            );
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOpera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOpera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bConsulta;
    private javax.swing.JButton bMovimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JMenuItem jMCerrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JLabel lSaldo;
    private javax.swing.JMenuItem miConsulta;
    private javax.swing.JMenuItem miMovimiento;
    private javax.swing.JPanel pCuenta;
    private javax.swing.JPanel pMov;
    private javax.swing.JPanel pTran;
    private javax.swing.JTextField tfCuenta;
    private javax.swing.JTextField tfImporte;
    // End of variables declaration//GEN-END:variables
}
