/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.*;
import java.util.regex.*;
import static javax.swing.JOptionPane.*;
import eje2.*;
import java.awt.Color;


public class V1 extends javax.swing.JFrame {

    /**
     * Creates new form V1
     */
    public V1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        jNombre = new javax.swing.JLabel();
        jApellido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDni = new javax.swing.JLabel();
        dninovalido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ALTA DE PERSONAS");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Apellidos");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Dni");

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        tfDni.setText("  .   .");
        tfDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDniFocusGained(evt);
            }
        });

        jNombre.setBackground(new java.awt.Color(255, 0, 0));

        jApellido.setBackground(new java.awt.Color(255, 0, 0));

        jDni.setBackground(new java.awt.Color(255, 0, 0));

        dninovalido.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)
                                .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNombre)
                            .addComponent(jApellido)
                            .addComponent(jLabel7)
                            .addComponent(jDni)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dninovalido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAceptar)
                                .addGap(42, 42, 42)
                                .addComponent(bSalir)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNombre))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jApellido))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jDni))
                .addGap(33, 33, 33)
                .addComponent(dninovalido)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bSalir))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDniFocusGained
        tfDni.setText("");
    }//GEN-LAST:event_tfDniFocusGained

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        try
        {
            defecto();
            
            boolean n = validardato(tfNombre.getText(),"NOMBRE","^[A-Za-z]+([ ][A-Za-z]+)?$");
            boolean a = validardato(tfApellidos.getText(),"APELLIDOS","^[A-Za-z]+([ ][A-Za-z]+)$");
            boolean d = validardni();
        
            if (n == true && a == true && d == true)
            {
                String nombre = tfNombre.getText();
                String apellidos = tfApellidos.getText();
                String dni = tfDni.getText();
               
                Eje2.altapersona(nombre, apellidos, dni);
                showMessageDialog(null,"Alta correcta");
                limpiar();
            }
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    public void defecto()
    {
        ocultarframe();
        cambiarborde();
    }
    
    public void ocultarframe()
    {
        jNombre.setVisible(false);
        jApellido.setVisible(false);
        jDni.setVisible(false);
        dninovalido.setVisible(false);
    }
    
    public void cambiarborde()
    {
        tfDni.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
        tfNombre.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
        tfApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }
    
    public void visualizartext(DatoNoValido dnv)
    {
        if (dnv.getCampo().equalsIgnoreCase("NOMBRE"))
            {
                jNombre.setText("NOMBRE no valido");
                jNombre.setForeground(Color.RED);
                jNombre.setVisible(true);
                tfNombre.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            }
        else
            {
                jApellido.setText("APELLIDO no valido");
                jApellido.setForeground(Color.RED);
                jApellido.setVisible(true);
                tfApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            }    
    }
    
    public void limpiar()
    {
        tfNombre.setText("");
        tfApellidos.setText("");
        tfDni.setText("");
    }
    
    public boolean validardato(String cuadro,String dato,String expre) throws Exception
    {   
        try{
            Pattern pt = Pattern.compile(expre);
            Matcher m = pt.matcher(cuadro);
            
            if (!m.matches())
                throw new DatoNoValido(dato);
            
            return true;
        }
        catch (DatoNoValido dnv)
        {
            visualizartext(dnv);
            return false;
        }
    }
    
    public boolean validardni() throws Exception
    {
        String dni = null;
        try{
            dni = tfDni.getText();

            Pattern pt = Pattern.compile("^[0-9]{8}[A-Z]$");
            Matcher m = pt.matcher(dni);

            if (!m.matches())
             throw new DatoNoValido("DNI");
            
            if (Eje2.validardni(dni))
                throw new Dninovalido();
            
            return true;
        }
        catch (DatoNoValido dnv)
        {
            jDni.setText("DNI no valido");
            jDni.setForeground(Color.RED);
            jDni.setVisible(true);
            tfDni.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            
            return false;
        }
        catch (Dninovalido dnva)
        {
            dninovalido.setText("Ya hay una persona dada de alta con ese dni");
            dninovalido.setVisible(true);
            tfDni.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            return false;
        }
    }
    
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        Eje2.salir();
    }//GEN-LAST:event_bSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel dninovalido;
    private javax.swing.JLabel jApellido;
    private javax.swing.JLabel jDni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jNombre;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
